"""Generate the static portfolio: python3 tools/build_site.py (no dependencies)."""
import json
from pathlib import Path
from html import escape as e
R=Path(__file__).resolve().parents[1]
projects=json.loads((R/'content/projects.json').read_text())
def page(name,title,body,active='',prefix=''):
 nav=''.join(f'<a href="{prefix}{path}"'+(' aria-current="page"' if label==active else '')+f'>{label}</a>' for label,path in [('Home','index.html'),('Work','work.html'),('About','about.html'),('Writing','writing.html'),('CV','cv.html')])
 html=f'''<!doctype html><html lang="en" class="privacy-locked"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{e(title)} · Zebang Wu</title><link rel="stylesheet" href="{prefix}assets/css/portfolio.css"><link rel="stylesheet" href="{prefix}assets/css/privacy-gate.css"><script defer src="{prefix}assets/js/privacy-gate.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="{prefix}index.html">Zebang Wu<span>Research / Engineering / Product</span></a><nav aria-label="Main navigation">{nav}</nav></header><main id="main">{body}</main><footer><span>Zebang Wu · 吴泽邦</span><a href="mailto:wuzebang@westlake.edu.cn">Get in touch ↗</a><span>Westlake University · Class of 2027</span></footer><noscript><p>This portfolio’s existing access gate requires JavaScript.</p></noscript></body></html>'''
 (R/name).parent.mkdir(parents=True,exist_ok=True);(R/name).write_text(html)
def card(p):
 return f'<a class="card" href="work/{p["id"]}.html"><span class="eyebrow">{e(p["category"])}</span><h3>{e(p["title"])}</h3><p>{e(p["confirmed_summary"])}</p><span class="read">Explore project ↗</span></a>'
# These are deliberately brief first-pass summaries, not completed case studies.
for p in projects:
 if p['id']=='reconstruction':p['confirmed_summary']='Comparing reconstruction methods under changes in sensor trajectories, with attention to evaluation protocols and adaptation trade-offs.'
 if p['id']=='dhh':p['confirmed_summary']='A faculty-supervised qualitative study of student well-being, using interviews and thematic analysis.'
 if p['id']=='feasypaste':p['dates']='Released March 2026';p['confirmed_summary']='A browser extension for transferring LLM responses into Feishu while preserving formulas, code blocks, and lists.'
page('index.html','Home','''<section class="hero"><p class="eyebrow">Electronic Information Engineering · Westlake University</p><h1>Understanding systems.<br><em>Building useful things.</em></h1><p class="intro">I’m Zebang Wu. My work spans machine learning evaluation, simulation systems, and interactive products. I’m interested in how intelligent systems behave in practice—and how people can use them effectively.</p><div class="actions"><a class="button" href="work.html">Explore my work ↗</a><a href="about.html">A little about me →</a></div></section><section><div class="section-head"><h2>Selected work</h2><a href="work.html">All projects →</a></div><div class="grid">'''+''.join(card(p) for p in projects if p['id'] in ['dongfeng','reconstruction','navix','feasypaste'])+'''</div></section><section class="note"><p class="eyebrow">A connected practice</p><h2>From experiments to experiences.</h2><p>Research teaches me to test assumptions. Engineering makes the constraints concrete. Product work brings the people using a system into the picture.</p><a href="cv.html">View my background →</a></section>''','Home')
page('work.html','Work','<section class="page-heading"><p class="eyebrow">Selected projects & experience</p><h1>Work</h1><p class="intro">Experiments, systems, and tools—across research, engineering, and product development.</p></section>'+''.join('<section><h2>'+cat+'</h2><div class="grid">'+''.join(card(p) for p in projects if p['category']==cat)+'</div></section>' for cat in ['Engineering','Research','Product']),'Work')
roles={'dongfeng':'R&D Intern · Dongfeng Motor Corporation R&D Institute','reconstruction':'Undergraduate Researcher · Westlake University','navix':'Product & Market Research Intern · Navix','dhh':'Lead Student Researcher · Westlake University','vr':'Research Assistant · Cornell University','active-learning':'Independent Researcher · Westlake University','feasypaste':'Solo developer','involve':'Frontend development · UI & interaction design'}
details={
'involve':[('The project','InVolve is a classroom interaction software project initially targeting higher education.'),('My contribution','I am responsible primarily for frontend development, UI, and interaction design. A collaborator is responsible for backend development.')],
'dongfeng':[('Connecting model and simulator','Integrated a vision-language-action model into Bench2Drive/CARLA, correcting trajectory coordinates, navigation mappings, and camera/ego-history synchronization.'),('Making evaluation more reliable','Built a persistent PyTorch inference service and a resumable evaluation pipeline, separating simulator and model dependencies and distinguishing driving failures from simulator and evaluation faults.'),('Investigating performance','Removed redundant multi-gigabyte array copies in ONNX inference. A route-level benchmark recorded approximately 68 seconds baseline mean latency and 5.7 seconds optimized warm-state median latency. These are different summary statistics from a specific benchmark, rather than a general performance guarantee.')],
'reconstruction':[('My contribution','Conducted baseline comparisons for physical-field reconstruction under sensor-trajectory shifts, evaluating randomized-trajectory fine-tuning and empirical Gaussian-process methods using shared evaluation protocols.'),('What I examined','Compared errors across scan and rotated trajectories, analyzing the trade-off between adaptation to new trajectories and performance on the original sensing distribution.')],
'navix':[('From needs to interactions','Translated eldercare and family-support needs into requirements and interactive prototypes, including user journeys, account permissions, AI conversations, and emergency-contact flows.'),('Prototyping AI-assisted workflows','Built Vue/TypeScript prototypes and a local scheduling service with seven MCP tools, using synthetic data, version-conflict checks, and retry handling.'),('Research for product decisions','Evaluated health-sensing and audio-service vendors and organized 27 health-management sources into a searchable reference library. These activities describe prototype development and research.')],
'dhh':[('Research approach','Led a faculty-supervised qualitative study, designing interviews and conducting thematic analysis.'),('Manuscript status','The first-author manuscript was under review at Applied Research in Quality of Life as of September 2026. A related systematic review, on which I am second author, was accepted at ASHA 2026 according to my September résumé.')],
'vr':[('My contribution','Reviewed embodiment, agency, and interactivity literature to inform research design; refined the instructional sequence and VR interactions, and verified relativistic parameters in Unity simulations.')],
'active-learning':[('Research direction','Developed self-supervised error-reduction sampling and evaluated it on an MLP-based DeepONet for Burgers’ equation.'),('Questions explored','Analyzed sample efficiency, continual-learning limitations, and computational cost. Earlier experiments explored a neural-network query policy; later work focused on error-reduction sampling.')],
'feasypaste':[('The problem','Equations, code blocks, and numbered lists can lose their structure when copied from an LLM conversation into Feishu.'),('The tool','FeasyPaste converts LLM responses into Feishu-compatible formatting. The published extension provides a concrete way to try the workflow.')]
}
for p in projects:
 link='<a class="button" href="https://chromewebstore.google.com/detail/feasypaste-feishu-convert/ehdmffeifoiagjgnkaajpdmhicdfajhb">View Chrome extension ↗</a>' if p['id']=='feasypaste' else ''
 body=f'<section class="page-heading"><a href="../work.html">← All work</a><p class="eyebrow">{e(p["category"])}</p><h1>{e(p["title"])}</h1><p class="intro">{e(p["confirmed_summary"])}</p><div class="meta"><span>{e(roles[p["id"]])}</span><span>{e(p["dates"])}</span></div></section><div class="prose">'+''.join(f'<section><h2>{e(h)}</h2><p>{e(t)}</p></section>' for h,t in details[p['id']])+link+'</div>'
 page('work/'+p['id']+'.html',p['title'],body,'Work','../')
page('about.html','About','''<section class="page-heading"><p class="eyebrow">A little about me</p><h1>Curiosity, with something<br><em>to show for it.</em></h1></section><div class="about-grid"><div class="prose"><p class="intro">I’m an Electronic Information Engineering undergraduate at Westlake University, expecting to graduate in May 2027. I spent Fall 2025 at Cornell University as an exchange student in Electrical & Computer Engineering.</p><h2>Learning through building</h2><p>My experience ranges from evaluating machine learning models and integrating simulation systems to designing interactive products. I enjoy moving between a technical question and the practical details that determine whether a system is useful.</p><h2>Working with people</h2><p>As president of Westlake’s College Student Union from August 2024 to August 2025, I organized six campus events for 30–300 attendees and introduced reporting and handover processes. My qualitative research with Deaf and Hard-of-Hearing students has also shaped how I approach questions about people and technology.</p><h2>Beyond projects</h2><p>I enjoy visual design, literature, music, and cycling. Posters and video edits have been another way to explore how ideas are communicated.</p></div><figure><img src="images/Selfie1.jpg" alt="Zebang Wu at Notre Dame, France"><figcaption>At Notre Dame, France</figcaption></figure></div>''','About')
page('writing.html','Writing','''<section class="page-heading"><p class="eyebrow">Notes & reflections</p><h1>Writing</h1><p class="intro">A place for ideas that need more room than a project summary.</p></section><section><a class="card" href="sharing/abandon.html"><span class="eyebrow">Essay · from the earlier site</span><h2>Abandon</h2><p>On continuity, purpose, and what remains.</p><span class="read">Read essay ↗</span></a></section>''','Writing')
page('cv.html','CV','''<section class="page-heading"><p class="eyebrow">Background · updated September 2026</p><h1>Curriculum vitae</h1><p class="intro">Electronic Information Engineering at Westlake University. Expected graduation: May 2027.</p></section><div class="prose"><section><h2>Education</h2><p><strong>Westlake University</strong> · B.S. in Electronic Information Engineering<br>GPA 4.06/4.3 · Expected May 2027</p><p><strong>Cornell University</strong> · Exchange student, Electrical & Computer Engineering<br>August–December 2025</p></section><section><h2>Experience & research</h2>'''+''.join(f'<p><a href="work/{p["id"]}.html"><strong>{e(p["title"])}</strong></a><br>{e(roles[p["id"]])}<br>{e(p["dates"])}</p>' for p in projects if p['id']!='feasypaste')+'''</section><section><h2>Leadership</h2><p>President, College Student Union, Westlake University · August 2024–August 2025</p></section><section><h2>Technical skills</h2><p>Python, C++, TypeScript, PyTorch, ONNX Runtime, MATLAB; CARLA, Vue, Git, Linux, Unity, Abaqus, LaTeX.</p><p>Mandarin Chinese (native) · English (fluent)</p></section></div>''','CV')
print('Generated 5 main pages and '+str(len(projects))+' project pages.')
